PREFIX uxmo:   <https://uxmethods.org/ontologies/uxmethods-core#>
# change this to just /ontologies/core#
PREFIX uxmd:   <https://uxmethods.org/method/>
# change this to /data/ ?
PREFIX uxmio:  <https://uxmethods.org/taxonomies/io#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>

# Finds method-to-method enablement links:
# m1 produces an output that m2 uses as an input.

SELECT ?m1Label ?m2Label ?sharedLabel
WHERE {
  ?m1 a uxmo:Method ; 
      uxmo:producesOutput ?shared ;
      rdfs:label ?m1Label .
  ?m2 a uxmo:Method ; 
      uxmo:usesInput      ?shared ;
      rdfs:label ?m2Label .
  ?shared skos:prefLabel ?sharedLabel .
  FILTER(?m1 != ?m2)
}
ORDER BY ?m1Label ?m2Label ?sharedLabel