name: API

on:
  push: 
    branches:
      - api

jobs:
  install-and-start:
    name: Install UX Methods API and Start Node
    runs-on: ubuntu-latest
    steps: 
      - name: Smoke Test
        run: echo ${{ secrets.UXM_PROJECT_ID }} > ~/test
      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.UXM_API_DREAMHOST_SSH_KEY }}" > ~/.ssh/uxm_api
          sudo chmod 600 ~/.ssh/uxm_api
          ssh-keyscan -H "jacksonville.dreamhost.com" > ~/.ssh/known_hosts
      - name: SFTP Upload
        run: sftp -i ~/.ssh/uxm_api uxm_api@jacksonville.dreamhost.com <<< $'cd api.uxmethods.org \n put -r ~/test'  