name: Build Web & Deploy to Staging

on:
  push: # action needs to run once successfully before worklflow_dispatch will work
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
        - name: Set Up SSH
          run: |
            mkdir -p ~/.ssh/
            echo "${{ secrets.UXM_DEV_DREAMHOST_SSH_KEY }}" > ~/.ssh/uxm_dev
            sudo chmod 600 ~/.ssh/uxm_dev
            ssh-keyscan -H "jacksonville.dreamhost.com" > ~/.ssh/known_hosts

        - name: SFTP Log In Check
          run: sftp -i ~/.ssh/uxm_dev uxm_dev@jacksonville.dreamhost.com <<< $'pwd'