name: Build Web & Deploy to Staging

on:
  push: # action needs to run once successfully before worklflow_dispatch will work
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    env:
      NODE_ENV: staging
    steps:
        - name: Checkout Code
          uses: actions/checkout@v2.3.1

        - name: Install Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '17.x'

        - name: Install Project Dependencies
          run: npm ci
          working-directory: web

        - name: Install Gatsby CLI
          run: npm install -g gatsby-cli@4.3.0
          working-directory: web

        - name: Build
          run: gatsby build
          working-directory: web
        
        - name: Verify build
          run: ls -la public
          working-directory: web

        - name: Set Up SSH
          run: |
            mkdir -p ~/.ssh/
            echo "${{ secrets.UXM_DEV_DREAMHOST_SSH_KEY }}" > ~/.ssh/uxm_dev
            sudo chmod 600 ~/.ssh/uxm_dev
            ssh-keyscan -H "jacksonville.dreamhost.com" > ~/.ssh/known_hosts

        - name: SFTP Upload
          run: sftp -i ~/.ssh/uxm_dev uxm_dev@jacksonville.dreamhost.com <<< $'cd dev.uxmethods.org \n put -r web/public/*'


# https://www.andrewvillazon.com/automatically-deploying-with-github-actions/
# https://help.dreamhost.com/hc/en-us/articles/216499537-How-to-configure-passwordless-login-in-Mac-OS-X-and-Linux
# Tip: get passwordless log-in working on local machine first. 