name: API

on:
  push: 
    branches:
      - api

jobs:
  install-and-start:
    name: Install UX Methods API and Start Node
    runs-on: ubuntu-latest
    steps: 
      # Uncomment if you need to recreate the .env file on DreamHost from GitHub repository secrets (or add to them)
      # - name: Write .env
      #   run: | 
      #     echo "PROJECT_ID=${{ secrets.UXM_PROJECT_ID }}" > .env
      #     echo "UXM_TOKEN=${{ secrets.SANTIY_UXM_API_TOKEN }}" >> .env
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.UXM_API_DREAMHOST_SSH_KEY }}" > ~/.ssh/uxm_api
          sudo chmod 600 ~/.ssh/uxm_api
          ssh-keyscan -H "jacksonville.dreamhost.com" > ~/.ssh/known_hosts
      - name: SFTP Upload API Scripts
        run: sftp -i ~/.ssh/uxm_api uxm_api@jacksonville.dreamhost.com <<< $'cd api.uxmethods.org \n mput *'
        working-directory: api
      - name: Install packages & start API
        run: ssh -i ~/.ssh/uxm_api uxm_api@jacksonville.dreamhost.com <<< 'cd api.uxmethods.org && npm install && touch tmp/restart.txt'