name: API

on:
  # push: 
  #   paths:
  #     - 'api/**'
  workflow_dispatch: 

jobs:
  install-and-start:
    name: Install UX Methods API and Start Node
    if: ${{ github.ref == 'refs/heads/main' }} 
    runs-on: ubuntu-latest
    steps: 
      # Uncomment if you need to recreate the .env file on DreamHost from GitHub repository secrets (or add to them)
      # - name: Write .env
      #   run: | 
      #     echo "PROJECT_ID=${{ secrets.UXM_PROJECT_ID }}" > .env
      #     echo "UXM_TOKEN=${{ secrets.SANTIY_UXM_API_TOKEN }}" >> .env
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.UXM_API_DREAMHOST_SSH_KEY }}" > ~/.ssh/uxm_api
          sudo chmod 600 ~/.ssh/uxm_api
          ssh-keyscan -H "jacksonville.dreamhost.com" > ~/.ssh/known_hosts
      - name: SFTP Upload API Scripts
        run: sftp -i ~/.ssh/uxm_api uxm_api@jacksonville.dreamhost.com <<< $'cd api.uxmethods.org \n mput *'
        working-directory: api
      - name: Install packages & start API
        run: ssh -i ~/.ssh/uxm_api uxm_api@jacksonville.dreamhost.com <<< 'cd api.uxmethods.org && npm install && touch tmp/restart.txt'


# nodemon app.js &> /dev/null & disown -ah && exit
# `command &> out` redirects both stdout & stderr (bash and zsh support this, but sh and ksh do not)
# --> https://askubuntu.com/questions/625224/how-to-redirect-stderr-to-a-file
# `disown -ah` removes all jobs from the shell and make them ignore SIGHUP
# --> https://devimalplanet.com/how-to-exit-terminal-leave-process-running
# consider adding a judicious `killall node` if/when I ever need to programmatically restart nodemon
# for now, it's picking up updates to app.js just fine