name: Build Web & Deploy to Staging

on:
  push: # action needs to run once successfully before worklflow_dispatch will work
  workflow_dispatch:

# Separate out levels into different jobs and set default there — do this once I have a basic, simpler flow working. cf. https://stackoverflow.com/a/69494898/5087128
# defaults:
#   run:
#     working-directory: web

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
        - name: Text Branch Workflow
          run: echo "Here's a test message"

        - name: Checkout Code
          uses: actions/checkout@v2.3.1

        - name: Install Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '17.x'

      # - name: Install Project Dependencies
      #   run: npm ci
      #     working-directory: web

      # - name: Install Gatsby CLI
      #   run: npm install -g gatsby-cli@4.3.0
      #     working-directory: web

      # - name: Build
      #   run: gatsby build
      #     working-directory: web
      
      # - name: Verify build
      #   run: ls -la public
      #     working-directory: web