name: Build Web & Deploy to Staging

on:
  push: # action needs to run once successfully before worklflow_dispatch will work
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
        - name: Set Up SSH
          run: |
            mkdir -p ~/.ssh/
            echo "${{ secrets.UXM_DEV_DREAMHOST_SSH_KEY }}" > ~/.ssh/deploy_key
            sudo chmod 600 ~/.ssh/deploy_key

        - name: SFTP Log In Check
          run: ssh -a ~/.ssh/deploy_key uxm_dev@jacksonville.dreamhost.com <<< $'pwd'