name: Studio

on:
  push:
    paths: 
      - 'studio/**'
  workflow_dispatch: 

jobs:
  build-and-deploy:
    name: Build & Deploy Sanity Studio
    if: ${{ github.ref == 'refs/heads/studio-v3' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install Project Dependencies
        run: npm ci --legacy-peer-deps
        working-directory: studio

      - name: Build Studio
        run: npx sanity build --no-auto-updates
        working-directory: studio

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DO_UXM_CMS_SSH_KEY }}" > ~/.ssh/do_uxm_cms
          sudo chmod 600 ~/.ssh/do_uxm_cms
          ssh-keyscan -H "24.199.98.130" > ~/.ssh/known_hosts

      - name: SFTP Upload
        run: sftp -i ~/.ssh/do_uxm_cms cms@24.199.98.130 <<< $'cd /var/www/cms/html \n put -r studio/dist/*'
