name: Build & Deploy Sanity Studio

on:
  push:
    branches:
      - studio # to remove after development
      - main
    workflow_dispatch: # will be available once workflow is merged with main

jobs:
  build-and-deploy:
    name: Build & Deploy Sanity Studio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Install Project Dependencies
        run: npm ci
        working-directory: studio

      - name: Install Sanity CLI
        run: npm install -g @sanity/cli
        working-directory: studio

      - name: Build Studio
        run: sanity build
        working-directory: studio

      - name: Verify Build
        run: ls -la dist
        working-directory: studio