name: Methods ETL

on: workflow_dispatch

jobs:
  methods-etl:
    runs-on: ubuntu-latest
    name: Extract, transform, and load Method output data.
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Extract & Transform
        uses: ./actions/method-transform
        id: extract-transform
      # Upload artifact as needed for debugging
      - name: Upload RDF file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: rdfData
          path: rdfData.ttl
      - name: Upload RDF to Data.World
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://api.data.world/v0/uploads/andyfitzgerald/method-io-data/files'
          method: 'POST'
          contentType: 'multipart/form-data'
          bearerToken : ${{ secrets.DATA_WORLD_READ_WRITE }}
          files: '{ "file": "rdfData.ttl" }'