on:
  # push: — Disabling for active developemnt
  workflow_dispatch:
  repository_dispatch:
    types: [method]

jobs:
  load-rdf-job:
    runs-on: ubuntu-latest
    name: Transform and load Sanity content as RDF
    steps:
      - name: Get Sanity Data
        id: sanityData
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://4g5tw1k0.api.sanity.io/v2021-03-25/data/query/production?query=*%5B_type%20%3D%3D%20%24type%5D%7B%0A%20%20title%2C%0A%20%20_id%2C%0A%20%20%22methodId%22%3A%20slug.current%2C%0A%20%20%22inputs%22%3A%20transputReference.inputsReference%5B%5D-%3E%7B%0A%20%20%20%20prefLabel%2C%0A%20%20%20%20%22inputId%22%3A%20conceptId.current%0A%20%20%7D%2C%0A%20%20%22outputs%22%3A%20transputReference.outputReference%5B%5D-%3E%7B%0A%20%20%20%20prefLabel%2C%0A%20%20%20%20%22outputId%22%3A%20conceptId.current%0A%20%20%7D%0A%7D&%24broader=%22transputTaxonomy_Recommendation%22&%24pageSlug=%22card-sorting%22&%24type=%22method%22'
          method: 'GET'
      # Echo data in action log to verify content
      - name: Show Response
        run: echo ${{ steps.sanityData.outputs.response }}
      # Checkout the repository so the workflow can access actions in it.
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Transform RDF
        uses: ./actions/rdf-transform # Uses an action in the root directory
        id: transform
        with:
          test-input: 'Here is a custom input message.'
          sanity-data: ${{ steps.sanityData.outputs.response }}
      - name: Upload RDF file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: rdfData
          path: rdfData.ttl
      - name: Upload RDF to Data.World
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://api.data.world/v0/uploads/andyfitzgerald/methods-transput-data/files'
          method: 'POST'
          contentType: 'multipart/form-data'
          bearerToken : ${{ secrets.DATA_WORLD_READ_WRITE }}
          files: '{ "file": "rdfData.ttl" }'

# Use Gatsby-source-remote-file to get .csv from data.world: https://www.gatsbyjs.com/plugins/gatsby-source-remote-file/
# Then gatsby-transformer-csv to read it into data I can query: https://www.gatsbyjs.com/plugins/gatsby-transformer-csv/
