name: Build & Deploy Sanity Studio
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build & Deploy Sanity Studio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install Project Dependencies
        run: npm ci
        working-directory: studio
      - name: Install Sanity CLI
        run: npm install @sanity/cli
        working-directory: studio
      - name: Build Studio
        run: sanity build
        working-directory: studio
      - name: Verify Build
        run: ls -la dist
        working-directory: studio
      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SANITY_CMS_DREAMHOST_SSH_KEY }}" > ~/.ssh/sanity_cms
          ssh-keyscan -H "jacksonville.dreamhost.com" > ~/.ssh/known_hosts
      - name: SFTP Upload
        run: sftp -i ~/.ssh/sanity_cms sanity_cms@JACKSONVILLE.dreamhost.com <<< $'cd studio.uxmethods.org \n put -r studio/dist/*'